"""initial schema

Revision ID: 87f7dd3795a6
Revises: dfc8706f3333
Create Date: 2026-05-29 19:43:41.848183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87f7dd3795a6'
down_revision: Union[str, Sequence[str], None] = 'dfc8706f3333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_logs_reminder_date'), 'reminder_logs', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_reminder_logs_user_id'), 'reminder_logs', ['user_id'], unique=False)
    op.add_column('ai_analyses', sa.Column('period_start', sa.DateTime(), nullable=True))
    op.add_column('ai_analyses', sa.Column('period_end', sa.DateTime(), nullable=True))
    op.add_column('ai_analyses', sa.Column('entry_count', sa.Integer(), nullable=True))
    op.add_column('ai_analyses', sa.Column('raw_output', sa.JSON(), nullable=True))
    op.alter_column('ai_analyses', 'analysis_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analyses', 'analysis_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('ai_analyses', 'raw_output')
    op.drop_column('ai_analyses', 'entry_count')
    op.drop_column('ai_analyses', 'period_end')
    op.drop_column('ai_analyses', 'period_start')
    op.drop_index(op.f('ix_reminder_logs_user_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_reminder_date'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    # ### end Alembic commands ###
