"""add life_balance tables

Revision ID: a318bc88c71c
Revises: 0f9fc327d42f
Create Date: 2026-05-29 21:09:56.627372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a318bc88c71c'
down_revision: Union[str, Sequence[str], None] = '0f9fc327d42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_balance_snapshots_user_id'), 'life_balance_snapshots', ['user_id'], unique=False)
    op.create_table('life_balance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('area_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['life_balance_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_balance_scores_snapshot_id'), 'life_balance_scores', ['snapshot_id'], unique=False)
    op.alter_column('ai_analyses', 'analysis_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analyses', 'analysis_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_life_balance_scores_snapshot_id'), table_name='life_balance_scores')
    op.drop_table('life_balance_scores')
    op.drop_index(op.f('ix_life_balance_snapshots_user_id'), table_name='life_balance_snapshots')
    op.drop_table('life_balance_snapshots')
    # ### end Alembic commands ###
